In [ ]:
!apt install postgresql postgresql-contrib &>log
!service postgresql start
!sudo -u postgres psql -c "CREATE USER root WITH SUPERUSER"
# set connection
%reload_ext sql
%config SqlMagic.feedback=False
%config SqlMagic.autopandas=True
%sql postgresql+psycopg2://@/postgres

 * Starting PostgreSQL 14 database server
   ...done.
ERROR:  role "root" already exists

In [ ]:
%sql CREATE TABLE Customer (customer_id INTEGER, first_name VARCHAR(100), last_name VARCHAR(100), gender VARCHAR(6), DOB DATE, job_title VARCHAR(100), job_industry_category VARCHAR(100), wealth_segment VARCHAR(100), deceased_indicator VARCHAR(10), owns_car VARCHAR(100), address VARCHAR(100), postcode VARCHAR(10), state VARCHAR(100), country VARCHAR(100), property_valuation INTEGER);

%sql COPY Customer FROM '/content/customer.csv' DELIMITER ';' CSV HEADER;

 * postgresql+psycopg2://@/postgres
 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [ ]:
%sql SELECT * FROM Customer;

 * postgresql+psycopg2://@/postgres

,customer_id,first_name,last_name,gender,dob,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,address,postcode,state,country,property_valuation
0,1,Laraine,Medendorp,F,1953-10-12,Executive Secretary,Health,Mass Customer,N,Yes,060 Morning Avenue,2016,New South Wales,Australia,10
1,2,Eli,Bockman,Male,1980-12-16,Administrative Officer,Financial Services,Mass Customer,N,Yes,6 Meadow Vale Court,2153,New South Wales,Australia,10
2,3,Arlin,Dearle,Male,1954-01-20,Recruiting Manager,Property,Mass Customer,N,Yes,0 Holy Cross Court,4211,QLD,Australia,9
3,4,Talbot,None,Male,1961-10-03,None,IT,Mass Customer,N,No,17979 Del Mar Point,2448,New South Wales,Australia,4
4,5,Sheila-kathryn,Calton,Female,1977-05-13,Senior Editor,n/a,Affluent Customer,N,Yes,9 Oakridge Court,3216,VIC,Australia,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,Rosalia,Halgarth,Female,1975-08-09,VP Product Management,Health,Mass Customer,N,No,57042 Village Green Point,4511,QLD,Australia,6
3996,3997,Blanch,Nisuis,Female,2001-07-13,Statistician II,Manufacturing,High Net Worth,N,Yes,87 Crescent Oaks Alley,2756,NSW,Australia,10
3997,3998,Sarene,Woolley,U,None,Assistant Manager,IT,High Net Worth,N,No,8194 Lien Street,4032,QLD,Australia,7
3998,3999,Patrizius,None,Male,1973-10-24,None,Manufacturing,Affluent Customer,N,Yes,320 Acker Drive,2251,NSW,Australia,7
3999,4000,Kippy,Oldland,Male,1991-11-05,Software Engineer IV,n/a,Affluent Customer,N,No,613 Erie Lane,3996,NSW,Australia,10

In [ ]:
import csv
import pandas as pd


with open('transaction.csv', 'r') as file:
    reader = csv.reader(file, delimiter=';')
    data = list(reader)

for row in data:
    row[10] = row[10].replace(',', '.')
    row[11] = row[11].replace(',', '.')

with open('transaction.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data)

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost
0,1,2,2950,2.25.17,False,Approved,Solex,Standard,medium,medium,71.49,53.62
1,2,3,3120,5.21.17,True,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92
2,3,37,402,10.16.17,False,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82
3,4,88,3135,8.31.17,False,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.10
4,5,78,787,10.1.17,True,Approved,Giant Bicycles,Standard,medium,large,1765.30,709.48
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,51,1018,6.24.17,True,Approved,OHM Cycles,Standard,high,medium,2005.66,1203.40
19996,19997,41,127,11.9.17,True,Approved,Solex,Road,medium,medium,416.98,312.74
19997,19998,87,2284,4.14.17,True,Approved,OHM Cycles,Standard,medium,medium,1636.90,44.71
19998,19999,6,2764,7.3.17,False,Approved,OHM Cycles,Standard,high,medium,227.88,136.73
19999,20000,11,1144,9.22.17,True,Approved,Trek Bicycles,Standard,medium,small,1775.81,1580.47

In [ ]:
%sql CREATE TABLE Transaction (transaction_id INTEGER, product_id INTEGER, customer_id INTEGER, transaction_date DATE, online_order BOOLEAN, order_status VARCHAR(100), brand VARCHAR(100), product_line VARCHAR(100), product_class VARCHAR(100), product_size VARCHAR(100), list_price NUMERIC(10, 2), standard_cost NUMERIC(10, 2));

%sql COPY Transaction FROM '/content/transaction.csv' DELIMITER ',' CSV HEADER;

 * postgresql+psycopg2://@/postgres
 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

In [ ]:
%sql SELECT * FROM Transaction;

 * postgresql+psycopg2://@/postgres

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost
0,1,2,2950,2017-02-25,False,Approved,Solex,Standard,medium,medium,71.49,53.62
1,2,3,3120,2017-05-21,True,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92
2,3,37,402,2017-10-16,False,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82
3,4,88,3135,2017-08-31,False,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.10
4,5,78,787,2017-10-01,True,Approved,Giant Bicycles,Standard,medium,large,1765.30,709.48
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,51,1018,2017-06-24,True,Approved,OHM Cycles,Standard,high,medium,2005.66,1203.40
19996,19997,41,127,2017-11-09,True,Approved,Solex,Road,medium,medium,416.98,312.74
19997,19998,87,2284,2017-04-14,True,Approved,OHM Cycles,Standard,medium,medium,1636.90,44.71
19998,19999,6,2764,2017-07-03,False,Approved,OHM Cycles,Standard,high,medium,227.88,136.73
19999,20000,11,1144,2017-09-22,True,Approved,Trek Bicycles,Standard,medium,small,1775.81,1580.47

In [ ]:
%sql UPDATE Transaction SET customer_id = 3034 WHERE customer_id = 5034;

%sql ALTER TABLE Customer ADD CONSTRAINT pk_customer_id PRIMARY KEY (customer_id);

%sql ALTER TABLE Transaction ADD CONSTRAINT pk_transaction_id PRIMARY KEY (transaction_id);

%sql ALTER TABLE Transaction ADD CONSTRAINT fk_customer_id FOREIGN KEY (customer_id) REFERENCES Customer(customer_id);

 * postgresql+psycopg2://@/postgres
 * postgresql+psycopg2://@/postgres
 * postgresql+psycopg2://@/postgres
 * postgresql+psycopg2://@/postgres

Empty DataFrame
Columns: []
Index: []

**Вывести все уникальные бренды, у которых стандартная стоимость выше 1500 долларов:**

In [ ]:
%sql SELECT DISTINCT brand FROM Transaction WHERE standard_cost > 1500;

 * postgresql+psycopg2://@/postgres

            brand
0      OHM Cycles
1   Trek Bicycles
2           Solex
3  Giant Bicycles

**Вывести все подтвержденные транзакции за период '2017-04-01' по '2017-04-09' включительно:**

In [ ]:
%sql SELECT * FROM Transaction WHERE order_status = 'Approved' AND transaction_date BETWEEN '2017-04-01' AND '2017-04-09'

 * postgresql+psycopg2://@/postgres

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost
0,17,79,2426,2017-04-03,False,Approved,Norco Bicycles,Standard,medium,medium,1555.58,818.01
1,19,54,2268,2017-04-06,True,Approved,WeareA2B,Standard,medium,medium,1292.84,13.44
2,23,37,2001,2017-04-08,True,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82
3,83,0,3398,2017-04-01,True,Approved,OHM Cycles,Standard,medium,medium,235.63,125.07
4,89,0,2682,2017-04-04,True,Approved,OHM Cycles,Road,high,large,12.01,7.21
...,...,...,...,...,...,...,...,...,...,...,...,...
526,19655,0,336,2017-04-09,True,Approved,Norco Bicycles,Standard,medium,medium,360.40,270.30
527,19853,7,3072,2017-04-02,False,Approved,Trek Bicycles,Road,low,medium,980.37,234.43
528,19899,57,325,2017-04-06,False,Approved,WeareA2B,Touring,medium,large,1890.39,260.14
529,19968,0,2751,2017-04-06,False,Approved,WeareA2B,Standard,medium,medium,60.34,45.26
530,19988,0,13,2017-04-05,True,Approved,Norco Bicycles,Road,medium,medium,544.05,376.84

**Вывести все профессии у клиентов из сферы IT или Financial Services, которые начинаются с фразы 'Senior:**

In [ ]:
%sql SELECT job_title FROM Customer WHERE job_industry_category IN ('IT', 'Financial Services') AND job_title LIKE 'Senior%'

 * postgresql+psycopg2://@/postgres

                   job_title
0    Senior Quality Engineer
1     Senior Cost Accountant
2   Senior Financial Analyst
3   Senior Financial Analyst
4     Senior Sales Associate
..                       ...
76   Senior Quality Engineer
77  Senior Financial Analyst
78  Senior Financial Analyst
79             Senior Editor
80  Senior Financial Analyst

[81 rows x 1 columns]

**Вывести все бренды, которые закупают клиенты, работающие в сфере Financial Services:**

In [ ]:
%sql SELECT DISTINCT brand FROM Transaction WHERE customer_id IN (SELECT customer_id FROM Customer WHERE job_industry_category = 'Financial Services')

 * postgresql+psycopg2://@/postgres

            brand
0            None
1   Trek Bicycles
2        WeareA2B
3           Solex
4  Giant Bicycles
5      OHM Cycles
6  Norco Bicycles

**Вывести 10 клиентов, которые оформили онлайн-заказ продукции из брендов 'Giant Bicycles', 'Norco Bicycles', 'Trek Bicycles':**

In [ ]:
%sql SELECT c.* FROM Customer c JOIN Transaction t ON c.customer_id = t.customer_id WHERE t.online_order = true AND t.brand IN ('Giant Bicycles', 'Norco Bicycles', 'Trek Bicycles') LIMIT 10

 * postgresql+psycopg2://@/postgres

,customer_id,first_name,last_name,gender,dob,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,address,postcode,state,country,property_valuation
0,3120,Lauree,O'Donnell,Female,1979-02-04,Clinical Specialist,Health,Mass Customer,N,Yes,32 Elmside Point,2560,NSW,Australia,6
1,787,Norma,Batrim,Female,1996-12-15,None,Retail,Affluent Customer,N,Yes,79 Arkansas Drive,3008,VIC,Australia,10
2,2339,Damien,Haddeston,Male,1958-12-28,Web Designer II,Property,Affluent Customer,N,Yes,533 Ramsey Center,4507,QLD,Australia,5
3,1243,Robbert,Blakey,Male,1953-08-09,Research Assistant II,Retail,Mass Customer,N,No,90351 Duke Junction,4820,QLD,Australia,1
4,3002,Tracey,Verdun,Male,1956-12-06,Paralegal,Financial Services,Mass Customer,N,Yes,921 Reinke Road,2529,NSW,Australia,7
5,2666,Lyle,Eager,Male,1971-02-16,Occupational Therapist,Health,Mass Customer,N,No,6988 Waxwing Hill,4700,QLD,Australia,3
6,3368,Tanya,Boddis,Female,1967-07-17,Technical Writer,Financial Services,Affluent Customer,N,No,42554 Randy Road,2047,NSW,Australia,12
7,2810,Malvin,Burchill,Male,1961-08-26,None,Property,Mass Customer,N,Yes,46100 Jay Place,4075,QLD,Australia,6
8,2003,Lilli,Hargey,Female,1962-06-21,Statistician III,Manufacturing,High Net Worth,N,Yes,5157 Maple Wood Circle,2537,NSW,Australia,8
9,2448,Lorri,Iston,Female,1992-12-18,Structural Analysis Engineer,Property,High Net Worth,N,No,4898 Buell Terrace,3043,VIC,Australia,7

**Вывести всех клиентов, у которых нет транзакций:**

In [ ]:
%sql SELECT c.* FROM Customer c LEFT JOIN Transaction t ON c.customer_id = t.customer_id WHERE t.customer_id IS NULL;

 * postgresql+psycopg2://@/postgres

,customer_id,first_name,last_name,gender,dob,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,address,postcode,state,country,property_valuation
0,852,Andie,Bonney,Female,2000-11-04,Compensation Analyst,Financial Services,Affluent Customer,N,Yes,94 Anhalt Way,3139,VIC,Australia,7
1,869,Addia,Abels,Female,1984-03-11,Account Representative I,Financial Services,High Net Worth,N,Yes,02377 Maywood Trail,2287,NSW,Australia,7
2,1373,Shaylynn,Epsley,Female,1958-09-23,Director of Sales,Financial Services,Mass Customer,N,Yes,0 Grasskamp Pass,3170,VIC,Australia,10
3,2074,Roslyn,Rawdall,Female,1997-06-11,None,Financial Services,Mass Customer,N,No,95483 Washington Junction,2505,NSW,Australia,9
4,2660,Hunt,Scollard,Male,1963-11-15,None,Retail,High Net Worth,N,Yes,359 Briar Crest Road,2155,NSW,Australia,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,3996,Rosalia,Halgarth,Female,1975-08-09,VP Product Management,Health,Mass Customer,N,No,57042 Village Green Point,4511,QLD,Australia,6
503,3997,Blanch,Nisuis,Female,2001-07-13,Statistician II,Manufacturing,High Net Worth,N,Yes,87 Crescent Oaks Alley,2756,NSW,Australia,10
504,3998,Sarene,Woolley,U,None,Assistant Manager,IT,High Net Worth,N,No,8194 Lien Street,4032,QLD,Australia,7
505,3999,Patrizius,None,Male,1973-10-24,None,Manufacturing,Affluent Customer,N,Yes,320 Acker Drive,2251,NSW,Australia,7
506,4000,Kippy,Oldland,Male,1991-11-05,Software Engineer IV,n/a,Affluent Customer,N,No,613 Erie Lane,3996,NSW,Australia,10

**Вывести всех клиентов из IT, у которых транзакции с максимальной стандартной стоимостью:**

In [ ]:
%sql SELECT c.* FROM Customer c JOIN Transaction t ON c.customer_id = t.customer_id WHERE c.job_industry_category = 'IT' AND t.standard_cost = (SELECT MAX(standard_cost) FROM Transaction WHERE customer_id = c.customer_id)

 * postgresql+psycopg2://@/postgres

,customer_id,first_name,last_name,gender,dob,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,address,postcode,state,country,property_valuation
0,3406,Lucy,Lackmann,Female,1979-04-28,Business Systems Development Analyst,IT,Mass Customer,N,Yes,1351 Lunder Road,2049,NSW,Australia,10
1,3473,Sanderson,Alloway,U,None,Analog Circuit Design manager,IT,Mass Customer,N,No,3 Roxbury Street,2261,NSW,Australia,7
2,22,Deeanne,Durtnell,Female,1962-12-10,None,IT,Mass Customer,N,No,52 Carey Alley,4740,QLD,Australia,5
3,2487,Elton,Piggford,Male,1978-01-13,Operator,IT,Affluent Customer,N,Yes,30624 John Wall Point,3101,VIC,Australia,7
4,2426,Yancy,Ovett,U,None,None,IT,Affluent Customer,N,Yes,57769 Gulseth Lane,2040,NSW,Australia,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,2084,Britni,Menguy,Female,1986-10-03,None,IT,Mass Customer,N,Yes,59 Prentice Lane,4551,QLD,Australia,7
189,255,Keeley,Kruger,Female,1954-01-15,Desktop Support Technician,IT,Mass Customer,N,No,8208 Parkside Point,2320,NSW,Australia,6
190,569,Jaime,Warkup,Male,1976-01-31,Analog Circuit Design manager,IT,Mass Customer,N,No,8498 Hoepker Circle,3136,Victoria,Australia,8
191,1210,Shandie,Sprigg,U,None,Programmer II,IT,Mass Customer,N,No,275 Lindbergh Parkway,2086,NSW,Australia,11
192,883,Lolita,Bennie,U,None,Recruiter,IT,Mass Customer,N,Yes,707 Spaight Place,2830,NSW,Australia,4

**Вывести всех клиентов из сферы IT и Health, у которых есть подтвержденные транзакции за период '2017-07-07' по '2017-07-17':**

In [ ]:
%sql SELECT c.* FROM Customer c JOIN Transaction t ON c.customer_id = t.customer_id WHERE c.job_industry_category IN ('IT', 'Health') AND t.order_status = 'Approved' AND t.transaction_date BETWEEN '2017-07-07' AND '2017-07-17'

 * postgresql+psycopg2://@/postgres

,customer_id,first_name,last_name,gender,dob,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,address,postcode,state,country,property_valuation
0,2000,Kain,Rene,U,None,Assistant Professor,IT,High Net Worth,N,Yes,32 Sutteridge Trail,2470,NSW,Australia,1
1,2337,Odilia,Bick,Female,2000-01-11,Programmer Analyst II,Health,Mass Customer,N,No,35 Lakewood Gardens Junction,3806,VIC,Australia,9
2,893,Gibby,Fearnley,Male,1983-09-11,Geologist I,IT,Mass Customer,N,No,6382 Bayside Street,2153,NSW,Australia,10
3,3166,Bronson,Plowman,Male,1955-05-11,Social Worker,Health,Mass Customer,N,No,13 Marcy Alley,3138,VIC,Australia,8
4,1555,Marcello,Spenclay,Male,1962-08-19,Tax Accountant,Health,High Net Worth,N,No,2 Darwin Parkway,2118,NSW,Australia,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,1174,Shellysheldon,Gooderridge,U,None,Executive Secretary,IT,Mass Customer,N,No,0005 Independence Drive,2118,NSW,Australia,9
120,1044,Frederico,Whilder,U,None,Food Chemist,Health,High Net Worth,N,No,31111 Hoepker Road,3034,VIC,Australia,9
121,1862,Daron,Umpleby,Female,1980-06-29,None,Health,High Net Worth,N,Yes,007 Canary Circle,2047,NSW,Australia,12
122,712,Norine,Antonik,Female,1961-05-20,None,IT,Mass Customer,N,No,4033 Hermina Road,2304,NSW,Australia,7
123,2442,Odie,Enrrico,Male,1957-10-13,Social Worker,Health,Affluent Customer,N,Yes,047 Kedzie Park,2206,NSW,Australia,11